### ISSUE TITLE
ImageTest.cc was not checked in.

### ISSUE THREAD

**Issue by zjzzjz1979** [fuzziqersoftware/phosg#1]
make failed

**Comment by zjzzjz1979** [comment]
also cyclone cannot be compiled with the latest Image interface update...

**Comment by fuzziqersoftware** [comment]
Added ImageTest in a44cc0f. Looks like I updated the FileCache interface but forgot to push the cyclone commit that uses the new interface; also pushed that just now. I noticed that cyclone's RateLimiterTest may spuriously fail on Ubuntu too; I'll look into this as well. Feel free to reopen this if there are other issues remaining besides RateLimiterTest.

**Comment by fuzziqersoftware** [comment]
The spurious test in cyclone should be fixed now as well. Sorry for the trouble!
