### ISSUE TITLE
JSONPickleTest - pickle protocol must be <= 5

### ISSUE THREAD

**Issue by einstein95** [fuzziqersoftware/phosg#10]
I was unable to reopen #9 so making a new issue
```
./JSONPickleTest
-- null
-- null (parse pickled representation)
-- null (parse pickled representation)
-- null (parse pickled representation)
-- null (parse serialized representation)
-- null (python3 deserialize; unsorted)
-- null (python3 serialize; protocol 0)
terminate called after throwing an instance of 'std::runtime_error'
  what():  command returned code 256
stdout:

stderr:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: pickle protocol must be <= 5

make: *** [Makefile:50: test] Aborted
```

**Comment by fuzziqersoftware** [comment]
What version of Python do you have installed? (`python3 --version`)

**Comment by nolrinale** [comment]
> What version of Python do you have installed? (`python3 --version`)

Python 3.9.7 running on M1 BigSur 11.6

I'm getting exactly the same error as OP while trying to make phosg to be able to compile the tapserver project for PSO and Dolphin.

**Comment by einstein95** [comment]
I'm gonna close this now as compiling in Arch Linux with 3.10.2 works perfectly
