### ISSUE TITLE
make error in Ubuntu

### ISSUE THREAD

**Issue by cr-gomezm** [fuzziqersoftware/phosg#2]
Hello and thanks for all the work, I am very new in working with Linux, just want to deploy a PSO newserv to test and play around a little bit and I have found that I need first to build and deploy phosg. During make, it stops on "Encoding.cc", it seems to me like an error on source files but I am not sure if this will work on Ubuntu (tested on 18.04 and 19.10, fully updated, same error on both), I have tried other forks of the projects with the same result :(.
![phosg_ubuntu_make_error](https://user-images.githubusercontent.com/63717095/79329524-3e563080-7f18-11ea-8f86-c6df1ccde31c.PNG)

**Comment by fuzziqersoftware** [comment]
I usually don't test my projects on Ubuntu, hence this issue. I've updated both phosg and newserv today and both should now build properly on Ubuntu.
