### ISSUE TITLE
Make error on armv6l

### ISSUE THREAD

**Issue by supermahars** [fuzziqersoftware/phosg#25]
Specifically in Image.cc, when making it this error is thrown:

/home/aaron/phosg/src/Image.cc: In instantiation of ‘void Image::save_helper(Image::Format, Writer&&) const [with Writer = Image::save(FILE*, Image::Format) const::<lambda(const void*, size_t)>]’:
/home/aaron/phosg/src/Image.cc:745:4:   required from here
/home/aaron/phosg/src/Image.cc:715:34: error: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘const ssize_t’ {aka ‘const int’} [-Werror=sign-compare]
  715 |       for (unsigned int y = 0; y < this->height; ++y) {
      |                                ~~^~~~~~~~~~~~~~
/home/aaron/phosg/src/Image.cc: In instantiation of ‘void Image::save_helper(Image::Format, Writer&&) const [with Writer = Image::save(Image::Format) const::<lambda(const void*, size_t)>]’:
/home/aaron/phosg/src/Image.cc:754:4:   required from here
/home/aaron/phosg/src/Image.cc:715:34: error: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘const ssize_t’ {aka ‘const int’} [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/phosg.dir/build.make:121: CMakeFiles/phosg.dir/src/Image.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/phosg.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

These appear to just be warnings; modifying the CmakLists.txt file allows me to bypass the warnings and continue without error

**Comment by fuzziqersoftware** [comment]
Thanks for the report; this is fixed in commit b38fb30b.
