### ISSUE TITLE
#include <cstdint> missing from src/Hash.hh

### ISSUE THREAD

**Issue by ZikZakFR** [fuzziqersoftware/phosg#28]
Compiling fails due to #include <cstdint>  not declared in src/Hash.hh

After adding it I can compile phosg.

**Comment by fuzziqersoftware** [comment]
Thanks for the report - fixed. Out of curiosity, which platform and compiler are you using?

**Comment by ZikZakFR** [comment]
> Thanks for the report - fixed. Out of curiosity, which platform and compiler are you using?

Archlinux
cmake version 3.27.1
gcc (GCC) 13.2.1 20230801

Do you need more information?

**Comment by fuzziqersoftware** [comment]
No, this is helpful. It looks like I should set up an Arch system for build testing; some of my other projects also seem to work on most Linuxes but have problems on Arch.

**Comment by ZikZakFR** [comment]
> No, this is helpful. It looks like I should set up an Arch system for build testing; some of my other projects also seem to work on most Linuxes but have problems on Arch.

Very true, I have issues recently with newserv. Now that phosg compiles, newserv fails to.
