### ISSUE TITLE
No phosg.cmake created

### ISSUE THREAD

**Issue by ZikZakFR** [fuzziqersoftware/phosg#29]
newserv can't find phosg.cmake during cmake .
Looking into phosg sources after compilation I can find CTestTestfile.cmake but no phosg.cmake.

**Comment by fuzziqersoftware** [comment]
Sorry for the delay - did you get this resolved? There was a bug a while ago where phosg-config.cmake wasn't installed immediately after building, and I had to run `sudo make install` twice, but I think this was fixed.

**Comment by ZikZakFR** [comment]
No worries. Earlier I noted that the file existed under a temporary name so I simply renamed it.
Now if I delete that file and also the installed one I get this from a new install:

-- Up-to-date: /usr/lib/phosg-config.cmake
-- Installing: /usr/lib/phosg.cmake
-- Up-to-date: /usr/lib/phosg-debug.cmake
