### ISSUE TITLE
Make Failing Windows

### ISSUE THREAD

**Issue by ryu777mtg** [fuzziqersoftware/phosg#30]
PC Specs
OS Windows 11
CPU AMD Ryzen 9 3950X 16 Core
RAM 64GB

Cygwin Setup version 2.926 (64 bit)

Installed what was listed in the main description. Upon running make this is the last error if their is a better log file I can provide I would but don't see one. I'm trying to build this to build the newserv by you. I tried to use the latest release but it states I'm missing cygz.dll. Which I know that should be posted at the newserv issue page but at least explaining the reason for attempting to do the manual build route. I tried source and non source versions of what's provided via CygWin as well.

```
[ 86%] Building CXX object CMakeFiles/ProcessTest.dir/src/ProcessTest.cc.o
/home/cyg/phosg/src/ProcessTest.cc: In function ‘int main(int, char**)’:
/home/cyg/phosg/src/ProcessTest.cc:231:22: error: unused parameter ‘argv’ [-Werror=unused-parameter]
  231 | int main(int, char** argv) {
      |               ~~~~~~~^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/ProcessTest.dir/build.make:76: CMakeFiles/ProcessTest.dir/src/ProcessTest.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:509: CMakeFiles/ProcessTest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by fuzziqersoftware** [comment]
Thanks for the report; this is fixed now. Separately, I've also created a newserv release which contains cygz.dll.
