### ISSUE TITLE
Error in Strings.cc

### ISSUE THREAD

**Issue by JimmieJoeJr** [fuzziqersoftware/phosg#6]
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Strings.o Strings.cc
Strings.cc: In function ‘size_t parse_size(const char*)’:
Strings.cc:790:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511627776’ to ‘0’ [-Werror=overflow]
 #define TB_SIZE (GB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:864:18: note: in expansion of macro ‘TB_SIZE’
     unit_scale = TB_SIZE;
                  ^~~~~~~
Strings.cc:791:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1125899906842624’ to ‘0’ [-Werror=overflow]
 #define PB_SIZE (TB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:866:18: note: in expansion of macro ‘PB_SIZE’
     unit_scale = PB_SIZE;
                  ^~~~~~~
Strings.cc:792:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1152921504606846976’ to ‘0’ [-Werror=overflow]
 #define EB_SIZE (PB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:868:18: note: in expansion of macro ‘EB_SIZE’
     unit_scale = EB_SIZE;
                  ^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: Strings.o] Error 1

**Comment by JimmieJoeJr** [comment]
The environment was built following this guide: https://cdromrom.wordpress.com/2020/12/05/phantasy-star-online-gamecube-server-on-raspberry-pi/

**Comment by fuzziqersoftware** [comment]
Thanks for the report. I had dropped support for 32-bit environments a while ago, but I suppose I still need to support them for cases like this. I've fixed this case by reverting the relevant commit, but I don't have access to my own Raspberry Pi right now to test further. Feel free to reopen this if it still doesn't build.

**Comment by JimmieJoeJr** [comment]
Strings.cc: In function ‘size_t parse_size(const char*)’:
Strings.cc:790:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511627776’ to ‘0’ [-Werror=overflow]
 #define TB_SIZE (GB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:874:18: note: in expansion of macro ‘TB_SIZE’
     unit_scale = TB_SIZE;
                  ^~~~~~~
Strings.cc:791:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1125899906842624’ to ‘0’ [-Werror=overflow]
 #define PB_SIZE (TB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:876:18: note: in expansion of macro ‘PB_SIZE’
     unit_scale = PB_SIZE;
                  ^~~~~~~
Strings.cc:792:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1152921504606846976’ to ‘0’ [-Werror=overflow]
 #define EB_SIZE (PB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:878:18: note: in expansion of macro ‘EB_SIZE’
     unit_scale = EB_SIZE;
                  ^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: Strings.o] Error 1
pi@raspberrypi3-PiHDD:~/phosg $ sudo make install
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Strings.o Strings.cc
Strings.cc: In function ‘size_t parse_size(const char*)’:
Strings.cc:790:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511627776’ to ‘0’ [-Werror=overflow]
 #define TB_SIZE (GB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:874:18: note: in expansion of macro ‘TB_SIZE’
     unit_scale = TB_SIZE;
                  ^~~~~~~
Strings.cc:791:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1125899906842624’ to ‘0’ [-Werror=overflow]
 #define PB_SIZE (TB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:876:18: note: in expansion of macro ‘PB_SIZE’
     unit_scale = PB_SIZE;
                  ^~~~~~~
Strings.cc:792:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1152921504606846976’ to ‘0’ [-Werror=overflow]
 #define EB_SIZE (PB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:878:18: note: in expansion of macro ‘EB_SIZE’
     unit_scale = EB_SIZE;
                  ^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: Strings.o] Error 1

**Comment by JimmieJoeJr** [comment]
pi@raspberrypi3-PiHDD:~ $ cd phosg
pi@raspberrypi3-PiHDD:~/phosg $ make
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Concurrency.o Concurrency.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o ConsistentHashRing.o ConsistentHashRing.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Encoding.o Encoding.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o FileCache.o FileCache.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Filesystem.o Filesystem.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Hash.o Hash.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Image.o Image.cc
In file included from /usr/include/c++/8/unordered_map:47,
                 from Filesystem.hh:18,
                 from Image.cc:15:
/usr/include/c++/8/bits/unordered_map.h: In constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::initializer_list<typename std::_Hashtable<_Key, std::pair<const _Key, _Tp>, _Alloc, std::__detail::_Select1st, _Pred, _Hash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<std::__not_<std::__and_<std::__is_fast_hash<_Hash>, std::__is_nothrow_invocable<const _Hash&, const _Key&> > >::value, false, true> >::value_type>, std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = unsigned char; _Tp = long long unsigned int; _Hash = std::hash<unsigned char>; _Pred = std::equal_to<unsigned char>; _Alloc = std::allocator<std::pair<const unsigned char, long long unsigned int> >]’:
/usr/include/c++/8/bits/unordered_map.h:226:7: note: parameter passing for argument of type ‘std::initializer_list<std::pair<const unsigned char, long long unsigned int> >’ changed in GCC 7.1
       unordered_map(initializer_list<value_type> __l,
       ^~~~~~~~~~~~~
/usr/include/c++/8/bits/unordered_map.h:231:40: note: parameter passing for argument of type ‘std::initializer_list<std::pair<const unsigned char, long long unsigned int> >’ changed in GCC 7.1
       : _M_h(__l, __n, __hf, __eql, __a)
                                        ^
In file included from /usr/include/c++/8/unordered_map:46,
                 from Filesystem.hh:18,
                 from Image.cc:15:
/usr/include/c++/8/bits/hashtable.h: In constructor ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_Hashtable(std::initializer_list<_Value>, std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::size_type, const _H1&, const key_equal&, const allocator_type&) [with _Key = unsigned char; _Value = std::pair<const unsigned char, long long unsigned int>; _Alloc = std::allocator<std::pair<const unsigned char, long long unsigned int> >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<unsigned char>; _H1 = std::hash<unsigned char>; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<false, false, true>]’:
/usr/include/c++/8/bits/hashtable.h:459:7: note: parameter passing for argument of type ‘std::initializer_list<std::pair<const unsigned char, long long unsigned int> >’ changed in GCC 7.1
       _Hashtable(initializer_list<value_type> __l,
       ^~~~~~~~~~
Image.cc: In function ‘void __static_initialization_and_destruction_0(int, int)’:
Image.cc:284:2: note: parameter passing for argument of type ‘std::initializer_list<std::pair<const unsigned char, long long unsigned int> >’ changed in GCC 7.1
 });
  ^
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o JSONPickle.o JSONPickle.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o JSON.o JSON.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Network.o Network.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Process.o Process.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Random.o Random.cc
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Strings.o Strings.cc
Strings.cc: In function ‘size_t parse_size(const char*)’:
Strings.cc:790:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511627776’ to ‘0’ [-Werror=overflow]
 #define TB_SIZE (GB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:874:18: note: in expansion of macro ‘TB_SIZE’
     unit_scale = TB_SIZE;
                  ^~~~~~~
Strings.cc:791:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1125899906842624’ to ‘0’ [-Werror=overflow]
 #define PB_SIZE (TB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:876:18: note: in expansion of macro ‘PB_SIZE’
     unit_scale = PB_SIZE;
                  ^~~~~~~
Strings.cc:792:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1152921504606846976’ to ‘0’ [-Werror=overflow]
 #define EB_SIZE (PB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:878:18: note: in expansion of macro ‘EB_SIZE’
     unit_scale = EB_SIZE;
                  ^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: Strings.o] Error 1
pi@raspberrypi3-PiHDD:~/phosg $ sudo make install
g++ -fPIC -std=c++14 -g -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -Wall -Werror -DLINUX   -c -o Strings.o Strings.cc
Strings.cc: In function ‘size_t parse_size(const char*)’:
Strings.cc:790:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1099511627776’ to ‘0’ [-Werror=overflow]
 #define TB_SIZE (GB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:874:18: note: in expansion of macro ‘TB_SIZE’
     unit_scale = TB_SIZE;
                  ^~~~~~~
Strings.cc:791:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1125899906842624’ to ‘0’ [-Werror=overflow]
 #define PB_SIZE (TB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:876:18: note: in expansion of macro ‘PB_SIZE’
     unit_scale = PB_SIZE;
                  ^~~~~~~
Strings.cc:792:26: error: conversion from ‘long long unsigned int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘1152921504606846976’ to ‘0’ [-Werror=overflow]
 #define EB_SIZE (PB_SIZE * 1024ULL)
                 ~~~~~~~~~^~~~~~~~~~
Strings.cc:878:18: note: in expansion of macro ‘EB_SIZE’
     unit_scale = EB_SIZE;
                  ^~~~~~~
cc1plus: all warnings being treated as errors
make: *** [<builtin>: Strings.o] Error 1
